;(function($){
    hasOwn = {}.hasOwnProperty;
    //clears a [wtitle] panel generated by sisense of its svg element
    $.fn.sisenseClearPanel = function(options) {
        var opts = $.extend({}, $.fn.sisenseClearPanel.defaults, options);
        return this.each(function(i,d){
            $(d).find('svg').remove();
            if( typeof opts.css !== 'undefined' ) {
                for( var p in opts.css )  {
                    if(hasOwn.call(opts.css, p)) $(d).css(p,opts.css[p]);
                }
            }
        });
    };
    
    $.fn.sisenseClearPanel.defaults = {css: null};
    
}(jQuery));